import uuid from "react-native-uuid";
import { Exercise } from "../exercise";

export const data: Exercise[] = [
  {
    id: uuid.v4(),
    primary: "Quadriceps",
    name: "Squats (Barbell)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Barbell",
  },
  {
    id: uuid.v4(),
    primary: "Glutes",
    name: "Deadlift (Barbell)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Barbell",
  },
  {
    id: uuid.v4(),
    primary: "Chest",
    name: "Push Ups",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: null,
  },
  {
    id: uuid.v4(),
    primary: "Biceps",
    name: "Alternating Bicep Curls",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Dumbbell",
  },
  {
    id: uuid.v4(),
    primary: "Upper Back",
    name: "Seated Cable Row - V Grip (Cable)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Machine",
  },
  {
    id: uuid.v4(),
    primary: "Full Body",
    name: "Kettlebell Swing (Kettlebell)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Kettlebell",
  },
  {
    id: uuid.v4(),
    primary: "Lats",
    name: "Lat Pulldown (Machine)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Machine",
  },
  {
    id: uuid.v4(),
    primary: "Shoulders",
    name: "Arnold Press (Dumbbell)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Dumbbell",
  },
  {
    id: uuid.v4(),
    primary: "Triceps",
    name: "Rope Pushdown (Cable Machine)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Machine",
  },
  {
    id: uuid.v4(),
    primary: "Biceps",
    name: "Preacher Curl (EZ Bar)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "EZ Barbell",
  },
  {
    id: uuid.v4(),
    primary: "Abdominals",
    name: "Russian Twist (Medicine Ball)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Medicine Ball",
  },
  {
    id: uuid.v4(),
    primary: "Glutes",
    name: "Hip Thrust (Barbell)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Barbell",
  },
  {
    id: uuid.v4(),
    primary: "Lower Back",
    name: "Back Extension (Machine)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Machine",
  },
];
