import { ExerciseCard } from "@/src/types/exercisecard";

export const data: ExerciseCard[] = [
  {
    id: 1,
    primary: "Quadriceps",
    name: "Squats (Barbell)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Barbell",
  },
  {
    id: 2,
    primary: "Glutes",
    name: "Deadlift (Barbell)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Barbell",
  },
  {
    id: 3,
    primary: "Chest",
    name: "Push Ups",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: null,
  },
  {
    id: 4,
    primary: "Biceps",
    name: "Alternating Bicep Curls",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Dumbbell",
  },
  {
    id: 5,
    primary: "Upper Back",
    name: "Seated Cable Row - V Grip (Cable)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Machine",
  },
  {
    id: 6,
    primary: "Full Body",
    name: "Kettlebell Swing (Kettlebell)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Kettlebell",
  },
  {
    id: 7,
    primary: "Lats",
    name: "Lat Pulldown (Machine)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Machine",
  },
  {
    id: 8,
    primary: "Shoulders",
    name: "Arnold Press (Dumbbell)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Dumbbell",
  },
  {
    id: 9,
    primary: "Triceps",
    name: "Rope Pushdown (Cable Machine)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Machine",
  },
  {
    id: 10,
    primary: "Biceps",
    name: "Preacher Curl (EZ Bar)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "EZ Barbell",
  },
  {
    id: 11,
    primary: "Abdominals",
    name: "Russian Twist (Medicine Ball)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Medicine Ball",
  },
  {
    id: 12,
    primary: "Glutes",
    name: "Hip Thrust (Barbell)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Barbell",
  },
  {
    id: 13,
    primary: "Lower Back",
    name: "Back Extension (Machine)",
    isSelected: false,
    sets: [],
    riveUrl: "",
    secondary: null,
    equipment: "Machine",
  },
];
